# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b123be8d43529f7c41a9015a850cc56f7a3268d0d95d1b5c84134a1dcc9b749ca9f6da90c6959995b09eb0bef45c254df3192c2dfce1b5f687bb10d98f77939a

test:
  secret_key_base: 69710f67ddc8e95963374be912fe3e0054f2df6520fb21888ae5227feeca6a24269636409d6030b57ddf9dc6781e40c1d2300dcdd1ab0b02bbc50667c4000ab8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
